#!/usr/bin/env python3
"""
CRT Capture Analyzer — NASA-style post-processing for webcam captures of CRT monitors.

Extracts maximum diagnostic information from Logitech C270 captures of NTSC/PAL
color bars generated by ESP32 CRT Signal Core.

Techniques: CLAHE, false color heatmaps, channel separation, FFT frequency analysis,
vectorscope emulation, hue angle measurement, scanline extraction, demoire.

Usage:
    python analyze_crt_capture.py input.jpg [--output-dir ./results] [--standard ntsc]
    python analyze_crt_capture.py input.png --all          # run every analysis
    python analyze_crt_capture.py input.jpg --quick        # fast subset only
"""

import argparse
import cv2
import numpy as np
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# NTSC 75% Color Bar Reference (SMPTE EG-1)
# ---------------------------------------------------------------------------
# Phase angles relative to burst (degrees), luma in IRE
NTSC_75_BARS = {
    "white":   {"ire": 77.0, "phase": None,   "rgb": (191, 191, 191)},
    "yellow":  {"ire": 69.0, "phase": 167.1,  "rgb": (191, 191,   0)},
    "cyan":    {"ire": 56.0, "phase": 283.5,  "rgb": (  0, 191, 191)},
    "green":   {"ire": 48.0, "phase": 240.7,  "rgb": (  0, 191,   0)},
    "magenta": {"ire": 36.0, "phase":  60.7,  "rgb": (191,   0, 191)},
    "red":     {"ire": 28.0, "phase": 103.5,  "rgb": (191,   0,   0)},
    "blue":    {"ire": 15.0, "phase": 347.1,  "rgb": (  0,   0, 191)},
    "black":   {"ire":  7.5, "phase": None,   "rgb": (  0,   0,   0)},
}

# ESP32 DAC levels from crt_demo_pattern.c mapped to normalized 0-1
# k_luma_bar_levels: 18176(white) -> 6400(black), DAC range ~6400-18176
ESP32_LUMA_LEVELS = [18176, 16880, 14643, 13348, 11228, 9933, 7695, 6400]

# ---------------------------------------------------------------------------
# 1. BASIC ENHANCEMENT
# ---------------------------------------------------------------------------

def enhance_clahe(img, clip_limit=3.0, grid_size=(8, 8)):
    """CLAHE on luminance channel — reveals subtle luma variations."""
    lab = cv2.cvtColor(img, cv2.COLOR_BGR2LAB)
    l, a, b = cv2.split(lab)
    clahe = cv2.createCLAHE(clipLimit=clip_limit, tileGridSize=grid_size)
    l_enhanced = clahe.apply(l)
    enhanced = cv2.merge([l_enhanced, a, b])
    return cv2.cvtColor(enhanced, cv2.COLOR_LAB2BGR)


def enhance_multiscale_retinex(img, sigmas=(15, 80, 250)):
    """Multi-Scale Retinex — NASA Langley technique for dynamic range compression.

    Simultaneously provides:
    - Dynamic range compression (see into shadows and highlights)
    - Color constancy (normalize illuminant effects from webcam)
    - Detail enhancement in both bright and dark regions
    """
    img_f = img.astype(np.float64) + 1.0  # avoid log(0)
    retinex = np.zeros_like(img_f)

    for sigma in sigmas:
        blur = cv2.GaussianBlur(img_f, (0, 0), sigma)
        retinex += np.log10(img_f) - np.log10(blur + 1.0)

    retinex /= len(sigmas)

    # Normalize to 0-255
    for c in range(3):
        channel = retinex[:, :, c]
        lo, hi = np.percentile(channel, [1, 99])
        retinex[:, :, c] = np.clip((channel - lo) / (hi - lo + 1e-6) * 255, 0, 255)

    return retinex.astype(np.uint8)


def enhance_unsharp_mask(img, sigma=2.0, strength=1.5):
    """Unsharp mask — sharpens edges to reveal signal transitions."""
    blurred = cv2.GaussianBlur(img, (0, 0), sigma)
    sharpened = cv2.addWeighted(img, 1.0 + strength, blurred, -strength, 0)
    return np.clip(sharpened, 0, 255).astype(np.uint8)


# ---------------------------------------------------------------------------
# 2. FALSE COLOR / HEATMAP (signal level visualization)
# ---------------------------------------------------------------------------

def false_color_luma(img, colormap=cv2.COLORMAP_JET):
    """False color map of luminance — like broadcast waveform monitor colors.

    Maps luma levels to a thermal-style colormap so you can visually distinguish
    IRE levels that look identical in grayscale.
    """
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    return cv2.applyColorMap(gray, colormap)


def false_color_ire_zones(img):
    """Custom false color with IRE-zone boundaries marked.

    Zones:
    - Super black  (< 7.5 IRE):  deep blue
    - Black setup  (7.5 IRE):    dark gray
    - Low (7.5-30 IRE):          blue->cyan
    - Mid (30-70 IRE):           green->yellow
    - High (70-100 IRE):         orange->red
    - Super white (>100 IRE):    magenta (illegal)
    """
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY).astype(np.float32)

    # Map webcam luminance to approximate IRE (assumes gamma ~2.2 capture)
    # Normalize: 0->0 IRE, 255->~110 IRE
    ire = (gray / 255.0) * 110.0

    result = np.zeros((*gray.shape, 3), dtype=np.uint8)

    # Super black (< 7.5 IRE)
    mask = ire < 7.5 * 0.95
    result[mask] = [180, 0, 0]  # blue

    # Setup (around 7.5 IRE)
    mask = (ire >= 7.5 * 0.95) & (ire < 7.5 * 1.1)
    result[mask] = [80, 80, 80]

    # Low (7.5-30 IRE)
    mask = (ire >= 7.5 * 1.1) & (ire < 30)
    t = np.clip((ire[mask] - 7.5) / (30 - 7.5), 0, 1)
    result[mask] = np.stack([
        (200 * (1 - t)).astype(np.uint8),
        (200 * t).astype(np.uint8),
        np.zeros_like(t, dtype=np.uint8)
    ], axis=-1)

    # Mid (30-70 IRE)
    mask = (ire >= 30) & (ire < 70)
    t = np.clip((ire[mask] - 30) / (70 - 30), 0, 1)
    result[mask] = np.stack([
        np.zeros_like(t, dtype=np.uint8),
        (255 * (1 - t * 0.5)).astype(np.uint8),
        (255 * t).astype(np.uint8)
    ], axis=-1)

    # High (70-100 IRE)
    mask = (ire >= 70) & (ire < 100)
    t = np.clip((ire[mask] - 70) / (100 - 70), 0, 1)
    result[mask] = np.stack([
        np.zeros_like(t, dtype=np.uint8),
        (128 * (1 - t)).astype(np.uint8),
        np.full_like(t, 255, dtype=np.uint8)
    ], axis=-1)

    # Super white (> 100 IRE — illegal in NTSC)
    mask = ire >= 100
    result[mask] = [200, 0, 200]  # magenta

    return result


# ---------------------------------------------------------------------------
# 3. CHANNEL SEPARATION
# ---------------------------------------------------------------------------

def extract_channels_yuv(img):
    """Separate Y, U, V channels — the native domain of composite video."""
    yuv = cv2.cvtColor(img, cv2.COLOR_BGR2YUV)
    y, u, v = cv2.split(yuv)
    return {
        "Y_luma": y,
        "U_chroma": u,
        "V_chroma": v,
    }


def extract_channels_yiq(img):
    """Convert to YIQ — the actual NTSC modulation color space.

    I and Q are what the NTSC subcarrier physically encodes.
    I = orange-cyan axis, Q = purple-green axis.
    IQ are UV rotated by 33 degrees.
    """
    bgr_f = img.astype(np.float64) / 255.0
    r, g, b = bgr_f[:, :, 2], bgr_f[:, :, 1], bgr_f[:, :, 0]

    y = 0.299 * r + 0.587 * g + 0.114 * b
    i = 0.5957 * r - 0.2745 * g - 0.3213 * b
    q = 0.2115 * r - 0.5226 * g + 0.3111 * b

    # Normalize I and Q from their ranges to 0-255 for visualization
    i_vis = np.clip((i + 0.5957) / (2 * 0.5957) * 255, 0, 255).astype(np.uint8)
    q_vis = np.clip((q + 0.5226) / (2 * 0.5226) * 255, 0, 255).astype(np.uint8)
    y_vis = np.clip(y * 255, 0, 255).astype(np.uint8)

    return {
        "Y_luma": y_vis,
        "I_inphase": i_vis,
        "Q_quadrature": q_vis,
        "_raw_y": y,
        "_raw_i": i,
        "_raw_q": q,
    }


def extract_channels_rgb(img):
    """Separate R, G, B channels — useful to check phosphor excitation."""
    b, g, r = cv2.split(img)
    return {"R": r, "G": g, "B": b}


def extract_channels_hsv(img):
    """Separate H, S, V — hue is key for chroma phase analysis."""
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    h, s, v = cv2.split(hsv)
    return {"Hue": h, "Saturation": s, "Value": v}


# ---------------------------------------------------------------------------
# 4. VECTORSCOPE EMULATION
# ---------------------------------------------------------------------------

def software_vectorscope(img, size=512):
    """Generate a vectorscope plot from the image — like a broadcast monitor.

    Plots Cb vs Cr (or U vs V) for every pixel. Color bar dots should cluster
    at known positions. Phase errors show as rotated clusters.
    """
    yuv = cv2.cvtColor(img, cv2.COLOR_BGR2YUV)
    _, u, v = cv2.split(yuv)

    scope = np.zeros((size, size, 3), dtype=np.uint8)

    # Draw crosshairs and graticule
    center = size // 2
    cv2.line(scope, (center, 0), (center, size), (40, 40, 40), 1)
    cv2.line(scope, (0, center), (size, center), (40, 40, 40), 1)

    # Draw target boxes for 75% NTSC bars
    scale = size / 256.0
    bar_targets = {
        "Yl": (44, 136),   "Cy": (166, 16),  "Gn": (38, 16),
        "Mg": (218, 240), "Rd": (90, 240), "Bl": (218, 120),
    }
    for name, (u_val, v_val) in bar_targets.items():
        x = int(u_val * scale)
        y = int((255 - v_val) * scale)
        cv2.rectangle(scope, (x - 8, y - 8), (x + 8, y + 8), (0, 80, 0), 1)
        cv2.putText(scope, name, (x + 10, y + 4),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.35, (0, 120, 0), 1)

    # Plot pixels
    u_flat = u.flatten().astype(np.float32)
    v_flat = v.flatten().astype(np.float32)

    # Subsample for performance (C270 is 1280x960 max)
    step = max(1, len(u_flat) // 500000)
    u_flat = u_flat[::step]
    v_flat = v_flat[::step]

    x_coords = (u_flat * scale).astype(np.int32)
    y_coords = ((255 - v_flat) * scale).astype(np.int32)

    # Clamp
    x_coords = np.clip(x_coords, 0, size - 1)
    y_coords = np.clip(y_coords, 0, size - 1)

    # Accumulate with color
    for x, y in zip(x_coords, y_coords):
        scope[y, x] = np.minimum(scope[y, x].astype(np.int32) + [2, 6, 2], 255).astype(np.uint8)

    return scope


# ---------------------------------------------------------------------------
# 5. HUE ANGLE MEASUREMENT
# ---------------------------------------------------------------------------

def measure_bar_hue_angles(img, num_bars=8, margin_pct=0.15):
    """Measure the actual hue angle of each color bar region.

    Computes both:
    - HSV hue (perceptual color wheel)
    - YIQ chrominance phase (NTSC subcarrier angle via atan2(Q, I))

    Returns a list of dicts with measurements per bar.
    """
    h, w = img.shape[:2]

    # Define ROI for the bars region (top 2/3, excluding ramp at bottom)
    bar_top = int(h * 0.1)
    bar_bottom = int(h * 0.6)

    # Extract bar regions
    bar_width = w // num_bars
    margin = int(bar_width * margin_pct)

    # Convert full image
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    bgr_f = img.astype(np.float64) / 255.0
    r = bgr_f[:, :, 2]
    g = bgr_f[:, :, 1]
    b = bgr_f[:, :, 0]

    # YIQ conversion
    y_raw = 0.299 * r + 0.587 * g + 0.114 * b
    i_raw = 0.5957 * r - 0.2745 * g - 0.3213 * b
    q_raw = 0.2115 * r - 0.5226 * g + 0.3111 * b

    bar_names = ["white", "yellow", "cyan", "green", "magenta", "red", "blue", "black"]
    results = []

    for idx in range(num_bars):
        x_start = idx * bar_width + margin
        x_end = (idx + 1) * bar_width - margin

        roi_hsv = hsv[bar_top:bar_bottom, x_start:x_end]
        roi_y = y_raw[bar_top:bar_bottom, x_start:x_end]
        roi_i = i_raw[bar_top:bar_bottom, x_start:x_end]
        roi_q = q_raw[bar_top:bar_bottom, x_start:x_end]
        roi_bgr = img[bar_top:bar_bottom, x_start:x_end]

        # HSV hue (OpenCV uses 0-179, multiply by 2 for 0-360)
        hue_mean = np.mean(roi_hsv[:, :, 0]) * 2.0
        sat_mean = np.mean(roi_hsv[:, :, 1])
        val_mean = np.mean(roi_hsv[:, :, 2])

        # YIQ chrominance phase angle
        i_mean = np.mean(roi_i)
        q_mean = np.mean(roi_q)
        chroma_phase = np.degrees(np.arctan2(q_mean, i_mean)) % 360

        # Chrominance amplitude
        chroma_amp = np.sqrt(i_mean**2 + q_mean**2)

        # Luma (approximate IRE)
        luma_mean = np.mean(roi_y)
        approx_ire = luma_mean * 92.5 + 7.5  # rough mapping 0->7.5, 1->100

        # Mean BGR
        mean_bgr = np.mean(roi_bgr.reshape(-1, 3), axis=0)

        name = bar_names[idx] if idx < len(bar_names) else f"bar_{idx}"
        ref = NTSC_75_BARS.get(name, {})

        result = {
            "bar": name,
            "hsv_hue_deg": round(hue_mean, 1),
            "hsv_sat": round(sat_mean, 1),
            "hsv_val": round(val_mean, 1),
            "yiq_phase_deg": round(chroma_phase, 1),
            "yiq_chroma_amp": round(chroma_amp, 4),
            "approx_ire": round(approx_ire, 1),
            "mean_bgr": [round(x, 1) for x in mean_bgr.tolist()],
            "ref_phase": ref.get("phase"),
            "ref_ire": ref.get("ire"),
            "phase_error": None,
        }

        if ref.get("phase") is not None and chroma_amp > 0.01:
            err = chroma_phase - ref["phase"]
            # Wrap to -180..180
            err = (err + 180) % 360 - 180
            result["phase_error"] = round(err, 1)

        results.append(result)

    return results


def draw_bar_analysis_overlay(img, measurements):
    """Draw measured values on top of the original image."""
    overlay = img.copy()
    h, w = overlay.shape[:2]
    num_bars = len(measurements)
    bar_width = w // num_bars

    for idx, m in enumerate(measurements):
        x = idx * bar_width + bar_width // 2
        y_base = int(h * 0.65)

        # Bar name
        cv2.putText(overlay, m["bar"].upper(),
                    (x - 25, y_base),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.4, (255, 255, 255), 1)

        # IRE level
        cv2.putText(overlay, f"{m['approx_ire']:.0f} IRE",
                    (x - 25, y_base + 18),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.35, (200, 200, 200), 1)

        # Phase angle (skip achromatic bars)
        if m["ref_phase"] is not None:
            color = (0, 255, 0) if abs(m["phase_error"] or 999) < 10 else (0, 0, 255)
            cv2.putText(overlay, f"Ph:{m['yiq_phase_deg']:.0f}",
                        (x - 25, y_base + 34),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.35, color, 1)
            if m["phase_error"] is not None:
                cv2.putText(overlay, f"Err:{m['phase_error']:+.1f}",
                            (x - 25, y_base + 48),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.3, color, 1)

    return overlay


# ---------------------------------------------------------------------------
# 6. WAVEFORM MONITOR EMULATION
# ---------------------------------------------------------------------------

def software_waveform(img, height=256):
    """Generate a waveform monitor display — plots luma per column.

    Each column of the output corresponds to a column of the input.
    Pixel brightness is plotted vertically (0 at bottom, 255 at top).
    """
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    h, w = gray.shape
    scope = np.zeros((height, w, 3), dtype=np.uint8)

    for col in range(w):
        column = gray[:, col]
        for val in column:
            y = height - 1 - int(val * (height - 1) / 255)
            y = max(0, min(y, height - 1))
            scope[y, col] = np.minimum(
                scope[y, col].astype(np.int32) + [1, 4, 1], 255
            ).astype(np.uint8)

    # Draw IRE reference lines
    for ire, label in [(7.5, "7.5"), (50, "50"), (100, "100")]:
        y_pos = height - 1 - int((ire / 110.0) * (height - 1))
        y_pos = max(0, min(y_pos, height - 1))
        scope[y_pos, :] = np.maximum(scope[y_pos, :], [30, 30, 0])
        cv2.putText(scope, f"{label} IRE", (4, y_pos - 2),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.3, (0, 60, 60), 1)

    return scope


def luma_line_profile(img, line_y=None):
    """Extract a single horizontal line profile of luma values.

    Returns (x_array, luma_array) — plot these to see the exact waveform
    of one scanline as the CRT would trace it.
    """
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    if line_y is None:
        line_y = gray.shape[0] // 3  # default to upper third

    line = gray[line_y, :].astype(np.float32)
    x = np.arange(len(line))
    return x, line


# ---------------------------------------------------------------------------
# 7. FFT FREQUENCY DOMAIN ANALYSIS
# ---------------------------------------------------------------------------

def fft_magnitude_spectrum(img):
    """2D FFT magnitude spectrum — reveals periodic patterns.

    Bright spots in the spectrum = periodic structures:
    - Horizontal lines = scanline frequency
    - Diagonal patterns = moire from phosphor grid
    - Isolated peaks = subcarrier-related patterns (if visible)
    """
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY).astype(np.float32)

    # Pad to optimal FFT size
    rows, cols = gray.shape
    opt_rows = cv2.getOptimalDFTSize(rows)
    opt_cols = cv2.getOptimalDFTSize(cols)
    padded = np.zeros((opt_rows, opt_cols), dtype=np.float32)
    padded[:rows, :cols] = gray

    # FFT
    dft = np.fft.fft2(padded)
    dft_shift = np.fft.fftshift(dft)

    magnitude = np.abs(dft_shift)
    # Log scale for visualization
    magnitude = np.log1p(magnitude)

    # Normalize to 0-255
    magnitude = (magnitude / magnitude.max() * 255).astype(np.uint8)

    # Apply colormap for better visibility
    colored = cv2.applyColorMap(magnitude, cv2.COLORMAP_INFERNO)

    return colored


def fft_per_channel(img):
    """FFT magnitude spectrum for each color channel separately.

    Different channels may show different frequency content — the chroma
    subcarrier pattern affects R and B differently than G.
    """
    results = {}
    for ch_name, ch_idx in [("B", 0), ("G", 1), ("R", 2)]:
        channel = img[:, :, ch_idx].astype(np.float32)

        dft = np.fft.fft2(channel)
        dft_shift = np.fft.fftshift(dft)
        magnitude = np.log1p(np.abs(dft_shift))
        magnitude = (magnitude / magnitude.max() * 255).astype(np.uint8)
        results[ch_name] = cv2.applyColorMap(magnitude, cv2.COLORMAP_INFERNO)

    return results


def fft_notch_demoire(img, notch_radius=5, threshold_pct=99.5):
    """Remove moire patterns using FFT notch filtering.

    Automatically detects strong periodic peaks (likely moire from
    phosphor grid / scanlines) and suppresses them.
    """
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY).astype(np.float32)
    rows, cols = gray.shape

    dft = np.fft.fft2(gray)
    dft_shift = np.fft.fftshift(dft)
    magnitude = np.abs(dft_shift)

    # Find peaks above threshold (excluding DC)
    center_y, center_x = rows // 2, cols // 2
    threshold = np.percentile(magnitude, threshold_pct)

    # Create mask (1 = keep, 0 = suppress)
    mask = np.ones_like(magnitude)

    for y in range(rows):
        for x in range(cols):
            if magnitude[y, x] > threshold:
                dist = np.sqrt((y - center_y)**2 + (x - center_x)**2)
                if dist > 10:  # skip DC component
                    # Notch out this frequency
                    cv2.circle(mask, (x, y), notch_radius, 0, -1)
                    # Also notch the conjugate
                    cx = 2 * center_x - x
                    cy = 2 * center_y - y
                    if 0 <= cx < cols and 0 <= cy < rows:
                        cv2.circle(mask, (cx, cy), notch_radius, 0, -1)

    # Apply mask
    dft_shift *= mask
    dft_ishift = np.fft.ifftshift(dft_shift)
    result = np.abs(np.fft.ifft2(dft_ishift))
    result = np.clip(result, 0, 255).astype(np.uint8)

    return result


# ---------------------------------------------------------------------------
# 8. SCANLINE ANALYSIS
# ---------------------------------------------------------------------------

def extract_scanlines(img, min_period=2, max_period=10):
    """Detect and extract CRT scanline positions from the capture.

    Uses horizontal gradient to find the periodic bright/dark pattern.
    """
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY).astype(np.float32)

    # Average across columns to get vertical brightness profile
    v_profile = np.mean(gray, axis=1)

    # Find the dominant vertical frequency (scanline period)
    fft_v = np.abs(np.fft.rfft(v_profile - np.mean(v_profile)))
    freqs = np.fft.rfftfreq(len(v_profile))

    # Look for peaks in the expected scanline frequency range
    period_range = (freqs > 1.0 / max_period) & (freqs < 1.0 / min_period)
    if np.any(period_range):
        peak_idx = np.argmax(fft_v * period_range)
        scanline_freq = freqs[peak_idx]
        scanline_period = 1.0 / scanline_freq if scanline_freq > 0 else 0

        return {
            "vertical_profile": v_profile,
            "fft_magnitudes": fft_v,
            "frequencies": freqs,
            "dominant_period_px": round(scanline_period, 2),
            "dominant_freq": round(scanline_freq, 4),
        }

    return {
        "vertical_profile": v_profile,
        "fft_magnitudes": fft_v,
        "frequencies": freqs,
        "dominant_period_px": None,
        "dominant_freq": None,
    }


# ---------------------------------------------------------------------------
# 9. EDGE / TRANSITION ANALYSIS
# ---------------------------------------------------------------------------

def analyze_bar_transitions(img):
    """Measure the sharpness of color bar transitions.

    Sharp transitions = good bandwidth. Blurry = bandwidth limiting or
    poor camera focus. Ringing = overshoot from the webcam's processing.
    """
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    h, w = gray.shape

    # Take a horizontal slice through the middle of the bars
    mid_y = h // 3
    line = gray[mid_y, :].astype(np.float32)

    # Compute gradient (derivative)
    gradient = np.gradient(line)

    # Find transition points (large gradient magnitude)
    threshold = np.std(gradient) * 2
    transitions = np.where(np.abs(gradient) > threshold)[0]

    # Sobel edge detection for visualization
    sobel_x = cv2.Sobel(gray, cv2.CV_64F, 1, 0, ksize=3)
    sobel_y = cv2.Sobel(gray, cv2.CV_64F, 0, 1, ksize=3)
    edges = np.sqrt(sobel_x**2 + sobel_y**2)
    edges = np.clip(edges / edges.max() * 255, 0, 255).astype(np.uint8)

    return {
        "edge_map": edges,
        "line_profile": line,
        "gradient": gradient,
        "transition_positions": transitions,
        "mean_gradient_at_transitions": float(np.mean(np.abs(gradient[transitions]))) if len(transitions) > 0 else 0,
    }


# ---------------------------------------------------------------------------
# 10. HISTOGRAM ANALYSIS
# ---------------------------------------------------------------------------

def detailed_histogram(img):
    """Generate per-channel and luma histograms with reference markers.

    The histogram shape reveals:
    - Peaks at specific levels = color bar luma values (good)
    - Broad spread = noise or poor contrast
    - Clipping at 0 or 255 = webcam exposure issues
    """
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    hist_canvas = np.zeros((300, 512, 3), dtype=np.uint8)

    # Luma histogram
    hist_gray = cv2.calcHist([gray], [0], None, [256], [0, 256]).flatten()
    hist_gray = hist_gray / hist_gray.max() * 280

    for x in range(256):
        h = int(hist_gray[x])
        cv2.line(hist_canvas, (x * 2, 299), (x * 2, 299 - h), (200, 200, 200), 1)
        cv2.line(hist_canvas, (x * 2 + 1, 299), (x * 2 + 1, 299 - h), (200, 200, 200), 1)

    # Per-channel histograms
    colors = [(255, 0, 0), (0, 255, 0), (0, 0, 255)]
    for ch, color in enumerate(colors):
        hist = cv2.calcHist([img], [ch], None, [256], [0, 256]).flatten()
        hist = hist / hist.max() * 280
        for x in range(256):
            h = int(hist[x])
            cv2.line(hist_canvas, (x * 2, 299), (x * 2, 299 - h), color, 1)

    return hist_canvas


# ---------------------------------------------------------------------------
# 11. COMPOSITE: DIAGNOSTIC DASHBOARD
# ---------------------------------------------------------------------------

def create_diagnostic_dashboard(img):
    """Generate a single composite image with all key diagnostic views.

    Layout (2x3 grid):
    [Original  ] [CLAHE Enhanced] [False Color ]
    [Waveform  ] [Vectorscope   ] [FFT Spectrum]
    """
    target_h, target_w = 360, 480

    def resize(src):
        return cv2.resize(src, (target_w, target_h))

    original = resize(img)
    clahe = resize(enhance_clahe(img))
    fc = resize(false_color_luma(img))
    wf = resize(software_waveform(img, height=target_h))
    vs = resize(software_vectorscope(img, size=max(target_h, target_w)))
    fft = resize(fft_magnitude_spectrum(img))

    # Labels
    font = cv2.FONT_HERSHEY_SIMPLEX
    for panel, label in [(original, "ORIGINAL"), (clahe, "CLAHE"),
                         (fc, "FALSE COLOR"), (wf, "WAVEFORM"),
                         (vs, "VECTORSCOPE"), (fft, "FFT SPECTRUM")]:
        cv2.putText(panel, label, (8, 20), font, 0.5, (0, 255, 255), 1)

    top_row = np.hstack([original, clahe, fc])
    bottom_row = np.hstack([wf, vs, fft])
    dashboard = np.vstack([top_row, bottom_row])

    return dashboard


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def save_img(img, output_dir: Path, name: str):
    path = output_dir / f"{name}.png"
    cv2.imwrite(str(path), img)
    print(f"  -> {path}")


def run_analysis(input_path: str, output_dir: str, standard: str = "ntsc",
                 quick: bool = False, run_all: bool = True):
    img = cv2.imread(input_path)
    if img is None:
        print(f"ERROR: cannot read {input_path}")
        sys.exit(1)

    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    stem = Path(input_path).stem

    print(f"=== CRT Capture Analyzer ===")
    print(f"Input:    {input_path} ({img.shape[1]}x{img.shape[0]})")
    print(f"Standard: {standard.upper()}")
    print(f"Output:   {out}/\n")

    # --- Dashboard (always) ---
    print("[1/11] Diagnostic dashboard...")
    save_img(create_diagnostic_dashboard(img), out, f"{stem}_dashboard")

    # --- Enhancement ---
    print("[2/11] CLAHE enhancement...")
    save_img(enhance_clahe(img), out, f"{stem}_clahe")

    if not quick:
        print("[2b/11] Multi-Scale Retinex (NASA)...")
        save_img(enhance_multiscale_retinex(img), out, f"{stem}_retinex")

        print("[2c/11] Unsharp mask...")
        save_img(enhance_unsharp_mask(img), out, f"{stem}_unsharp")

    # --- False color ---
    print("[3/11] False color heatmaps...")
    save_img(false_color_luma(img), out, f"{stem}_false_color_jet")
    save_img(false_color_luma(img, cv2.COLORMAP_TURBO), out, f"{stem}_false_color_turbo")
    if not quick:
        save_img(false_color_ire_zones(img), out, f"{stem}_ire_zones")

    # --- Channel separation ---
    print("[4/11] Channel separation (YUV)...")
    yuv = extract_channels_yuv(img)
    for name, ch in yuv.items():
        save_img(ch, out, f"{stem}_{name}")

    if not quick:
        print("[4b/11] Channel separation (YIQ — NTSC native)...")
        yiq = extract_channels_yiq(img)
        for name, ch in yiq.items():
            if not name.startswith("_"):
                save_img(ch, out, f"{stem}_{name}")

        print("[4c/11] Channel separation (RGB)...")
        rgb = extract_channels_rgb(img)
        for name, ch in rgb.items():
            save_img(ch, out, f"{stem}_{name}")

        print("[4d/11] Channel separation (HSV)...")
        hsv_ch = extract_channels_hsv(img)
        for name, ch in hsv_ch.items():
            save_img(ch, out, f"{stem}_{name}")

    # --- Vectorscope ---
    print("[5/11] Software vectorscope...")
    save_img(software_vectorscope(img), out, f"{stem}_vectorscope")

    # --- Hue angle measurement ---
    print("[6/11] Bar hue angle measurement...")
    measurements = measure_bar_hue_angles(img)
    save_img(draw_bar_analysis_overlay(img, measurements), out, f"{stem}_bar_overlay")

    print("\n  === COLOR BAR MEASUREMENTS ===")
    print(f"  {'Bar':<10} {'IRE':>6} {'YIQ Phase':>10} {'Ref Phase':>10} {'Phase Err':>10} {'Chroma':>8}")
    print(f"  {'-'*10} {'-'*6} {'-'*10} {'-'*10} {'-'*10} {'-'*8}")
    for m in measurements:
        ref_ph = f"{m['ref_phase']:.1f}" if m["ref_phase"] else "  ---"
        err = f"{m['phase_error']:+.1f}" if m["phase_error"] is not None else "  ---"
        print(f"  {m['bar']:<10} {m['approx_ire']:>5.1f} "
              f"{m['yiq_phase_deg']:>9.1f} {ref_ph:>10} {err:>10} {m['yiq_chroma_amp']:>7.4f}")
    print()

    # --- Waveform ---
    print("[7/11] Waveform monitor...")
    save_img(software_waveform(img), out, f"{stem}_waveform")

    # --- FFT ---
    print("[8/11] FFT magnitude spectrum...")
    save_img(fft_magnitude_spectrum(img), out, f"{stem}_fft_spectrum")

    if not quick:
        print("[8b/11] Per-channel FFT...")
        fft_ch = fft_per_channel(img)
        for name, spectrum in fft_ch.items():
            save_img(spectrum, out, f"{stem}_fft_{name}")

        print("[8c/11] FFT demoire...")
        save_img(fft_notch_demoire(img), out, f"{stem}_demoire")

    # --- Scanlines ---
    print("[9/11] Scanline analysis...")
    scan_info = extract_scanlines(img)
    if scan_info["dominant_period_px"]:
        print(f"  Detected scanline period: {scan_info['dominant_period_px']} px")
    else:
        print("  No clear scanline periodicity detected")

    # --- Edges ---
    print("[10/11] Edge / transition analysis...")
    edge_info = analyze_bar_transitions(img)
    save_img(edge_info["edge_map"], out, f"{stem}_edges")
    print(f"  Mean gradient at transitions: {edge_info['mean_gradient_at_transitions']:.1f}")

    # --- Histogram ---
    print("[11/11] Detailed histogram...")
    save_img(detailed_histogram(img), out, f"{stem}_histogram")

    print(f"\nDone! All outputs in: {out}/")


def main():
    parser = argparse.ArgumentParser(
        description="CRT Capture Analyzer — NASA-style post-processing for signal diagnostics"
    )
    parser.add_argument("input", help="Input image (PNG/JPG from webcam capture)")
    parser.add_argument("--output-dir", "-o", default="./crt_analysis",
                        help="Output directory (default: ./crt_analysis)")
    parser.add_argument("--standard", "-s", choices=["ntsc", "pal"], default="ntsc",
                        help="Video standard (default: ntsc)")
    parser.add_argument("--quick", "-q", action="store_true",
                        help="Quick mode — skip slow analyses")
    parser.add_argument("--all", "-a", action="store_true",
                        help="Run all analyses (default)")

    args = parser.parse_args()
    run_analysis(args.input, args.output_dir, args.standard, args.quick, args.all)


if __name__ == "__main__":
    main()
